### ISSUE TITLE
SEO-Friendly HTML Output

### ISSUE THREAD

**Issue by totallyquiche** [pythad/nider#6]
Since image text cannot be seen by search engines, I think a useful feature would be the ability to output SEO-friendly HTML for embedding the generated image.

If you agree, please assign me to the Issue and I will implement this. 😃 

# Feature Description

Passing an ``html=True`` param to img methods will output a .txt file containing an `<img>` tag. The `title` and `alt` properties will be generated using the text from `header` and `para`, respectively.

## Example

```
from nider.models import Content
from nider.models import Header
from nider.models import Linkback
from nider.models import Paragraph
from nider.models import Image

header = Header('Your super interesting title!')
para = Paragraph('Lorem ipsum dolor sit amet.')
linkback = Linkback('foo.com | @username')
content = Content(para, header, linkback, padding=60)

img = Image(content, fullpath='result.png')

img.draw_on_bg('#212121', html=True)

```

## Output

```
result.png
result.txt
```

## result.txt

```
<img src="result.png" alt="Lorem ipsum dolor sit amet." title="Your super interesting title!" />
```

**Comment by pythad** [comment]
Hello! Thanks for sharing your ideas.

I thought about this for some time and that's what I have to say:

- There is no need for generating a separate `.txt` file. Anyway user will later need to parse it in order to get the string.
- Generating a full `<img>` tag is definitely not what someone will use:
  - You can't provide a correct `src` because it always will be relevant to the machine.
  - You almost always want to add some classes to `<img>` tags.


What would be cool to do is to add behavior that would add `title` and `description` attributes to the `Image` model, where `Image.title = Header.text` and `Image.description = Paragraph.text` so that later anyone can create their own `<img>` tags without worrying abou `title` and `alt`.

**Comment by totallyquiche** [comment]
That’s a much better idea! I’d be happy to give it a go.

**Comment by pythad** [comment]
Sure, you can give it a try. Waiting to see your pull request!

**Comment by codeofdusk** [comment]
As an aside, incorporating alt text helps [screen reader](http://enwp.org/screen_reader) users like me! Untagged text-based images are not good for us, because the content of those images is completely inaccessible (aside from OCR, which is severely hit and miss)
